version: '3'

services:
  # sentinel断路器,流量控制
  # http://127.0.0.1:8858/  默认账号密码: sentinel/sentinel
  sentinel-dashboard:
    image: bladex/sentinel-dashboard
    ports:
      - 8858:8858
    restart: always